name: Build
on: [push]
jobs:
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      
      - name: Initialize Env
        id: init-env
        uses: Silverlan/common_actions/set_common_env_vars@main

      - name: Build submodule - udm
        id: build-udm
        uses: Silverlan/util_udm/github_actions/build@master
        with:
          root_dir: "${{ inputs.root_dir }}/external_libs/util_udm"
          build_shared: '1'
          
      - name: CMake
        shell: bash
        run: |
          echo "library_file_path: ${{ steps.build-udm.outputs.library_file_path }}"
          echo "include_directory: ${{ steps.build-udm.outputs.include_directory }}"

