name: Build
on: [push]
jobs:
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Initialize Env
        id: init-env
        uses: Silverlan/common_actions/set_common_env_vars@main

      - name: Setup GeometricTools
        id: setup-gt
        shell: bash
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "::set-output name=gt_build_target::Mathematics"
          else
            echo "::set-output name=gt_build_target::GTE/GTMathematics.v14"
          fi

      - name: Build
        id: build
        uses: Silverlan/util_udm/github_actions/build@master
        with:
          root_dir: "${{ env.GA_ROOT_DIR }}"
          should_checkout: "0"
          dir: '.'
          
      - name: CMake
        shell: bash
        run: |
          echo "library_file_path: ${{ steps.build.outputs.library_file_path }}"
          echo "include_directory: ${{ steps.build.outputs.include_directory }}"

