name: Build
on: [push]
jobs:
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download sharedutils
        id: dl-shared
        uses: Silverlan/common_actions/get_submodule@main
        with:
          repo: 'https://github.com/Silverlan/sharedutils.git'
          repo_name: 'sharedutils'
          dir: 'external_libs'
          cmake_var: 'DEPENDENCY_SHAREDUTILS_INCLUDE'
          
      - name: CMake
        shell: bash
        run: |
          echo "Output: ${{ steps.dl-shared.outputs.include_directory }}"

