name: Build
on: [push]
jobs:
  build-windows:
    name: Build-Windows-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows x64 MSVC",
            os: windows-latest,
            artifact: "Windows-MSVC.tar.xz",
            build_type: "RelWithDebInfo",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            cc: "cl",
            cxx: "cl",
            archiver: "7z a",
            generators: "Visual Studio 16 2019"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download submodules
        run: |
          git submodule update --init --recursive
      - name: CMake
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}" \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: cmake --build ./ --config ${{ matrix.config.build_type }}
  build-ubuntu:
    name: Build-Ubuntu-x64
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu GCC-11",
            os: ubuntu-latest,
            artifact: "ubuntu_gcc.7z",
            build_type: "RelWithDebInfo",
            cc: "gcc-11",
            cxx: "g++-11",
            archiver: "7z a",
            generators: "Unix Makefiles"
          }
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download sharedutils
        id: dl-shared
        uses: Silverlan/common_actions/get_submodule@main
        with:
          repo: 'https://github.com/Silverlan/sharedutils.git'
          repo_name: 'sharedutils'
          dir: 'external_libs'
          cmake_var: 'DEPENDENCY_SHAREDUTILS_INCLUDE'
          
      - name: CMake
        shell: bash
        run: |
          echo "Output: ${{ steps.dl-shared.outputs.include_directory }}"
